version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    links:
      - dispatcher:dispatcher
    ports:
      - "8888:80"
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - books:books
      - frontend_books:frontend_books
    volumes:
      - ./config/dispatcher:/config
  database:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini

  books:
    image: madnificent/books-service:2.0.0
    links:
      - database:database

  frontend_books:
    image: janpieterbaert/delta-tutorial-books-frontend:producer
    links:
      - books:backend
